// Import the `createSlice` function from the "@reduxjs/toolkit" library
import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the authentication slice
const initialState = {
  isAuthenticated: false, // Initially not authenticated
  user: null, // No user information initially
};

// Create a slice using the `createSlice` function
const authSlice = createSlice({
  name: "auth", // Name of the slice
  initialState, // Initial state for the slice
  reducers: {
    // Define a reducer function to handle the "signIn" action
    signIn: (state, action) => {
      // Update the state to indicate authentication and set the user information
      state.isAuthenticated = true;
      state.user = action.payload;
    },
    // Define a reducer function to handle the "signOut" action
    signOut: (state) => {
      // Update the state to indicate no authentication and clear user information
      state.isAuthenticated = false;
      state.user = null;
    },
  },
});

// Export the action creators for "signIn" and "signOut" along with the reducer
export const { signIn, signOut } = authSlice.actions;

// Export a selector function to retrieve the entire authentication state
export const selectAuth = (state) => state.auth;

// Export the reducer function generated by the slice
export default authSlice.reducer;
