// Import the `createSlice` function from the "@reduxjs/toolkit" library
import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the theme slice
const initialState = {
  isLight: true, // Default theme is light
};

// Create a slice using the `createSlice` function
const themeSlice = createSlice({
  name: "theme", // Name of the slice
  initialState, // Initial state for the slice
  reducers: {
    // Define a reducer function to handle the "changeTheme" action
    changeTheme: (state, action) => {
      // Update the theme by toggling between light and dark based on the payload
      state.isLight = !action.payload;
    },
  },
});

// Export the action creator for "changeTheme" and the reducer
export const { changeTheme } = themeSlice.actions;

// Export a selector function to retrieve the entire theme state
export const selectTheme = (state) => state.theme;

// Export the reducer function generated by the slice
export default themeSlice.reducer;
